### ISSUE TITLE
nodes

### ISSUE THREAD

**Issue by grand96** [Heaven-sFeel/sankacoin#1]
Hi! Are there working nodes?

**Comment by Heaven-sFeel** [comment]
No yet, I'm in the building process right now, soon it'll be.

**Comment by Heaven-sFeel** [comment]
Hey! there's three nodes online right now.

**Comment by grand96** [comment]
Please write the addresses of these nodes

**Comment by Heaven-sFeel** [comment]
Just want is working right now due to some maintenance. 
IP address: 147.182.199.165

**Comment by grand96** [comment]
Work fine, thanks
